CREATE TABLE notes (
   id INT AUTO_INCREMENT PRIMARY KEY,
   user_id INT NOT NULL,
   display_id INT NOT NULL,
   category VARCHAR(50),
   title VARCHAR(255) NOT NULL,
   content TEXT,
   important BOOLEAN DEFAULT FALSE,
   color VARCHAR(50),
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (category) REFERENCES categories(name) ON DELETE SET NULL,
   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);